### ISSUE TITLE
Install fails when using Software Center in Ubuntu

### ISSUE THREAD

**Issue by m0schneider** [prey/prey-node-client#138]

**Comment by v6** [comment]
// , My installation not only fails, but repeatedly tries to reinstall every time that I try to use `sudo apt-get install` on other software. 

This has occurred on this system since about a month ago, at least. 

The spew, I get repeatedly, every time I attempt to install Prey on Ubuntu 14.10 ends with the following: 

chowning /usr/lib/prey/versions/1.4.0/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/duplexer2/node_modules to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.4.0/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/through2/node_modules to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.3.9/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/duplexer2 to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.3.9/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/through2 to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.4.0/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/duplexer2 to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.4.0/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/through2 to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.3.9/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.4.0/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.3.9/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.4.0/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.3.9/node_modules/nodemailer/node_modules/buildmail/node_modules to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.4.0/node_modules/nodemailer/node_modules/buildmail/node_modules to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.3.9/node_modules/nodemailer/node_modules/buildmail to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.4.0/node_modules/nodemailer/node_modules/buildmail to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.3.9/node_modules/nodemailer/node_modules to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.4.0/node_modules/nodemailer/node_modules to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.3.9/node_modules/nodemailer to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.4.0/node_modules/nodemailer to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.3.9/node_modules to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.4.0/node_modules to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.3.9 to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.4.0 to uid 999 and gid 999
chowning /usr/lib/prey/versions to uid 999 and gid 999
chowning /usr/lib/prey to uid 999 and gid 999
Setting permissions on /etc/prey
chowning /etc/prey/prey.conf to uid 999 and gid 999
chowning /etc/prey to uid 999 and gid 999
Setting permissions on /var/log/prey.log
chowning /var/log/prey.log to uid 999 and gid 999
Running "config activate" as prey
--
Ensuring presence of config dir: /etc/prey
Syncing /etc/prey/prey.conf with /usr/lib/prey/versions/1.3.9/prey.conf.default
Setting up this as current...
Warning: This version is already set as current.
Setting permissions on /usr/lib/prey/current
Running post_activate hooks...
Voila! All good.
--
Installing init scripts.
dpkg: error processing package prey (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up libqpidtypes1:amd64 (0.16-7.2build1) ...
Setting up libqpidcommon2:amd64 (0.16-7.2build1) ...
Setting up libsslcommon2:amd64 (0.16-7.2build1) ...
Setting up libssl-dev:amd64 (1.0.1f-1ubuntu9.8) ...
Setting up libssl-doc (1.0.1f-1ubuntu9.8) ...
Setting up uuid-dev:amd64 (2.25.1-3ubuntu4.1) ...
Setting up libsslcommon2-dev:amd64 (0.16-7.2build1) ...
Processing triggers for libc-bin (2.19-10ubuntu2.3) ...
Errors were encountered while processing:
 prey
E: Sub-process /usr/bin/dpkg returned an error code (1)


Here follows a link to the full log: 
https://mega.nz/#!TF4zjbSC!scS31lQqrg-44Hz0hF7I8MQORvcjn8JiM4BXmp0MQZ0
