### ISSUE TITLE
Prey GUI items do not open Arch Linux 64 bit

### ISSUE THREAD

**Issue by BtpPrograms** [prey/prey-node-client#228]
I'm running bspwm and systemd, let me know if you need any other specific information about my system or my issues.

I've had a few issues with Prey, both when installing through the AUR package and when installing through npm directly. I ran "prey config hooks post_install" and "prey config account setup." When I run "prey config gui" I get the following output.

```

(node:27970) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

Valid existing keys found. Proceeding anyway.

Firing up config GUI!
```

Nothing happens after this output. I also don't get any visual change from starting lock even though the web interface says that the command successfully activated. The same is true for sending a message. The sound alarm and location tracking work fine. I'm also getting frequent short disconnects from the laptop when I send commands. I've attached the log below, but it doesn't seem to show any errors except for not being able to add battery power to the report when the location is gotten.

[prey.txt](https://github.com/prey/prey-node-client/files/438458/prey.txt)

**Comment by jristz** [comment]
I can confirm that this also happend if I install with the provided package in the webpage, or if I run using the internal (in prey) node binary.

**Comment by brokencog** [comment]
Late to the problem here ... but hopefully helps someone else.

ensure:

- create user/group of prey/prey
- create /etc/prey/prey.config and give /etc/prey and /etc/prey/prey.conf ownership to prey user/group
- running the prey shell script as a **prey** user with **prey** group.
- if you use *sudo -u prey*, then the login user X11 Window Manager  session Xauthorization  must be granted to the prey user.  (as prey user:  xauth merge /home/otheruser/.Xauthority)

Good luck.

**Comment by adrfantini** [comment]
I can confirm this is happening and I cannot fix it using @brokencog 's suggestions.
